services:
  - type: web
    name: openmeet-backend
    env: node
    buildCommand: npm install && npm run clean && npx tsc
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 